flyway.url=jdbc:postgresql://postgres:5432/app
flyway.user=postgres
flyway.password=postgres
flyway.locations=filesystem:/flyway/sql
flyway.connectRetries=30
flyway.validateMigrationNaming=true
flyway.baselineOnMigrate=true
flyway.baselineVersion=1
